# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.

name: 30 SAST

on:
  # to make sure new SAST rules are applied also to production code -> make sure the default branch is "current Prod-Release".
  schedule:
    - cron: '35 12 * * 1'
  workflow_call:
  workflow_dispatch:

permissions:
    contents: read

jobs:
  SAST-CodeQL:
    name: Build and SAST CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java-kotlin', 'javascript-typescript' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.
          
          # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
          # queries: security-extended,security-and-quality     

      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        if: matrix.language == 'java-kotlin'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven          
      - name: Cache build
        if: matrix.language == 'java-kotlin'
        id: cache-build
        uses: actions/cache@v3
        with:
          path: todo/target
          key: ${{ runner.os }}-target
      - name: Cache m2
        if: matrix.language == 'java-kotlin'
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ~/.m2/**/*.jar
          key: ${{ runner.os }}-m2
      - name: Build with mvnw
        if: matrix.language == 'java-kotlin'
        working-directory: todo
        run: ./mvnw package -DskipTests    
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2.22.4
        with:
          category: "/language:${{matrix.language}}"
      - name: Upload artifact
        if: matrix.language == 'java-kotlin'
        uses: actions/upload-artifact@v3.1.3
        with:
          name: target
          path: ${{github.workspace}}/todo/target 

  spotbugs:
    name: SAST SpotBugs
    needs: [SAST-CodeQL]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run SpotBugs action
      uses: jmservera/spotbugs-github-action@v0.1.0-alpha
      with:
        packages: app.demo.todo.-
        target: ./todo/target
        dependenciesPath: ~/.m2
        basePath: src/main/java
    - name: Upload SpotBugs report
      uses: actions/upload-artifact@v3.1.3
      with:
        name: spotbugs.sarif
        path: ${{github.workspace}}/results.sarif
    - name: Upload analysis results to GitHub Security tab
      if: always()
      uses: github/codeql-action/upload-sarif@v2.22.4
      with:
        sarif_file: ${{github.workspace}}/results.sarif    

  semgrep:
    needs: [SAST-CodeQL]
    # User-definable name of this GitHub Actions job:
    name: SAST Semgrep
    # If you are self-hosting, change the following `runs-on` value: 
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: returntocorp/semgrep

    # To skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch project source with GitHub Actions Checkout.
      - uses: actions/checkout@v3
      - run: semgrep ci -o results.sarif --sarif || true
        env:
           # Add the rules that Semgrep uses by setting the SEMGREP_RULES environment variable. 
           SEMGREP_RULES: p/default p/security-audit # more at semgrep.dev/explore
           # Uncomment SEMGREP_TIMEOUT to set this job's timeout (in seconds):
           # Default timeout is 1800 seconds (30 minutes).
           # Set to 0 to disable the timeout.
           # SEMGREP_TIMEOUT: 300
      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v3.1.3
        if: always()
        with:
          name: semgrep.sarif
          path: ${{github.workspace}}/results.sarif
      - name: Upload analysis results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2.22.4
        with:
          sarif_file: ${{github.workspace}}/results.sarif