name: 50-Dependency-Review
on:
  schedule:
    - cron: '15 09 * * 1'
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - run: echo "${{ github.event_name }}"
      - name: 'Dependency Review from PR'
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v3