name: 'Dependency Review'
on:
  # to make sure new SAST rules are applied also to production code -> make sure the default branch is "current Prod-Release".
  schedule:
    - cron: '15 09 * * 1'
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3