name: 50-Dependency-Review
on:
  schedule:
    - cron: '15 09 * * 1'
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Dependency Review from base'
        if: github.event_name != 'pull_request'
        with:
            base-ref: https://github.com/jmservera/app-service-java-demo/commit/6300e436ea3086b2f9111903ded2178732dc23d1
        uses: actions/dependency-review-action@v3
      - name: 'Dependency Review from PR'
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v3